version: '3'
services:
  catalog:
    image: fcuenca4/${APP_NAME}:${APP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        NAME: ${APP_NAME}
        PORT: ${APP_PORT}
        VERSION: ${APP_VERSION}
    ports:
      - ${APP_PORT}:${APP_PORT}
